### ISSUE TITLE
open failed: enoent

### ISSUE THREAD

**Issue by santhosh-D-subramani** [Lrdsnow/PureNotes#1]
![image](https://github.com/user-attachments/assets/29649854-1062-43b6-8555-c87d084d4bfa)

running in SDK 35 google emulator

**Comment by Lrdsnow** [comment]
yes, it needs /sdcard/Documents/PureNotes.json to exist, this file is normally generated by AndroidRestore (which uses an iOS backup to restore as much as possible to Android, but you can select Notes only)
